# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BuckIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuckIt
pod ‘FBSDKCoreKit’
pod ‘FBSDKShareKit’
pod ‘FBSDKLoginKit’
pod 'Firebase/Auth’
pod 'GoogleSignIn'
pod 'SwipeCellKit'
pod 'PopupDialog', '~> 0.7'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
end
